function df = jacobianDP( x, a_w, par )
%FJACSYM
%    DF = FJACSYM(J_G1XX,J_G2XX,A_W,DPHI1_T,DPHI2_T,G,K_G1,K_G2,L1,L_S1,L_S2,M_G1,M_G2,PHI1_T,PHI2_T)

%    This function was generated by the Symbolic Math Toolbox version 8.0.
%    21-Nov-2022 22:25:07
phi1_t = x(3);
phi2_t = x(5);
dphi1_t = x(4);
dphi2_t = x(6);


l1 = par(1);
l2 = par(2);
l_S1 = par(3);
l_S2 = par(4);
m_G1 = par(5);
m_G2 = par(6);
J_G1xx = par(7);
J_G2xx = par(8);
k_G1 = par(9);
k_G2 = par(10);
g = par(11);




%Version: 1.1
t2 = l1.^2;
t3 = l_S2.^2;
t4 = m_G2.^2;
t7 = phi1_t-phi2_t;
t5 = cos(t7);
t6 = l_S1.^2;
t8 = cos(phi1_t);
t9 = sin(phi1_t);
t10 = t5.^2;
t11 = dphi1_t.^2;
t12 = sin(t7);
t13 = dphi2_t.^2;
t14 = J_G1xx.*J_G2xx;
t15 = t2.*t3.*t4;
t16 = J_G2xx.*m_G2.*t2;
t17 = J_G2xx.*m_G1.*t6;
t18 = J_G1xx.*m_G2.*t3;
t19 = m_G1.*m_G2.*t3.*t6;
t23 = t2.*t3.*t4.*t10;
t20 = t14+t15+t16+t17+t18+t19-t23;
t21 = cos(phi2_t);
t22 = sin(phi2_t);
t24 = 1.0./t20;
t25 = t12.^2;
t26 = t2.*t3.*t4.*t11.*t25;
t27 = dphi1_t.*k_G2.*l1.*l_S2.*m_G2.*t12;
t28 = g.*l1.*t3.*t4.*t12.*t22;
t29 = 1.0./t20.^2;
t30 = J_G2xx.*dphi1_t.*k_G1;
t31 = J_G2xx.*dphi1_t.*k_G2;
t32 = dphi1_t.*k_G1.*m_G2.*t3;
t33 = dphi1_t.*k_G2.*m_G2.*t3;
t34 = l1.*l_S2.*t3.*t4.*t12.*t13;
t35 = a_w.*l1.*t3.*t4.*t8;
t36 = J_G2xx.*a_w.*l1.*m_G2.*t8;
t37 = J_G2xx.*a_w.*l_S1.*m_G1.*t8;
t38 = dphi1_t.*k_G2.*l1.*l_S2.*m_G2.*t5;
t39 = t2.*t3.*t4.*t5.*t11.*t12;
t40 = a_w.*l_S1.*m_G1.*m_G2.*t3.*t8;
t41 = g.*l1.*t3.*t4.*t5.*t22;
t42 = J_G2xx.*l1.*l_S2.*m_G2.*t12.*t13;
t48 = dphi2_t.*k_G2.*l1.*l_S2.*m_G2.*t5;
t43 = t30+t31+t32+t33+t34+t35+t36+t37+t38+t39+t40+t41+t42-t48-J_G2xx.*dphi2_t.*k_G2-dphi2_t.*k_G2.*m_G2.*t3-J_G2xx.*g.*l1.*m_G2.*t9-J_G2xx.*g.*l_S1.*m_G1.*t9-g.*l1.*t3.*t4.*t9-g.*l_S1.*m_G1.*m_G2.*t3.*t9-a_w.*l1.*t3.*t4.*t5.*t21;
t44 = t2.*t3.*t4.*t5.*t12.*t29.*t43.*2.0;
t45 = J_G2xx.*k_G2;
t46 = k_G2.*m_G2.*t3;
t47 = k_G2.*l1.*l_S2.*m_G2.*t5;
t49 = t2.*t3.*t4.*t13.*t25;
t50 = dphi1_t.*k_G1.*l1.*l_S2.*m_G2.*t12;
t51 = a_w.*l_S2.*t2.*t4.*t8.*t12;
t52 = a_w.*l1.*l_S1.*l_S2.*m_G1.*m_G2.*t8.*t12;
t53 = J_G1xx.*dphi1_t.*k_G2;
t54 = dphi1_t.*k_G2.*m_G2.*t2;
t55 = dphi1_t.*k_G2.*m_G1.*t6;
t56 = l1.*l_S2.*t2.*t4.*t11.*t12;
t57 = g.*l_S2.*t2.*t4.*t22;
t58 = J_G1xx.*g.*l_S2.*m_G2.*t22;
t59 = dphi1_t.*k_G1.*l1.*l_S2.*m_G2.*t5;
t60 = a_w.*l_S2.*t2.*t4.*t5.*t8;
t61 = t2.*t3.*t4.*t5.*t12.*t13;
t62 = g.*l_S2.*m_G1.*m_G2.*t6.*t22;
t63 = J_G1xx.*l1.*l_S2.*m_G2.*t11.*t12;
t64 = l1.*l_S2.*m_G1.*m_G2.*t6.*t11.*t12;
t65 = a_w.*l1.*l_S1.*l_S2.*m_G1.*m_G2.*t5.*t8;
t66 = t38-t48+t53+t54+t55+t56+t57+t58+t59+t60+t61+t62+t63+t64+t65-J_G1xx.*dphi2_t.*k_G2-dphi2_t.*k_G2.*m_G2.*t2-dphi2_t.*k_G2.*m_G1.*t6-J_G1xx.*a_w.*l_S2.*m_G2.*t21-a_w.*l_S2.*t2.*t4.*t21-g.*l_S2.*t2.*t4.*t5.*t9-a_w.*l_S2.*m_G1.*m_G2.*t6.*t21-g.*l1.*l_S1.*l_S2.*m_G1.*m_G2.*t5.*t9;
t67 = J_G1xx.*k_G2;
t68 = k_G2.*m_G2.*t2;
t69 = k_G2.*m_G1.*t6;
df = reshape([0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,t44+t24.*(t26+t27+t28+J_G2xx.*a_w.*l1.*m_G2.*t9+J_G2xx.*a_w.*l_S1.*m_G1.*t9+J_G2xx.*g.*l1.*m_G2.*t8+J_G2xx.*g.*l_S1.*m_G1.*t8+a_w.*l1.*t3.*t4.*t9+g.*l1.*t3.*t4.*t8-t2.*t3.*t4.*t10.*t11-l1.*l_S2.*t3.*t4.*t5.*t13-J_G2xx.*l1.*l_S2.*m_G2.*t5.*t13-dphi2_t.*k_G2.*l1.*l_S2.*m_G2.*t12+a_w.*l_S1.*m_G1.*m_G2.*t3.*t9+g.*l_S1.*m_G1.*m_G2.*t3.*t8-a_w.*l1.*t3.*t4.*t12.*t21),0.0,-t24.*(t27+t49+t50+t51+t52-t2.*t3.*t4.*t10.*t13+g.*l_S2.*t2.*t4.*t5.*t8-g.*l_S2.*t2.*t4.*t9.*t12-l1.*l_S2.*t2.*t4.*t5.*t11-J_G1xx.*l1.*l_S2.*m_G2.*t5.*t11-dphi2_t.*k_G2.*l1.*l_S2.*m_G2.*t12+a_w.*l_S2.*t2.*t4.*t5.*t9-l1.*l_S2.*m_G1.*m_G2.*t5.*t6.*t11+a_w.*l1.*l_S1.*l_S2.*m_G1.*m_G2.*t5.*t9+g.*l1.*l_S1.*l_S2.*m_G1.*m_G2.*t5.*t8-g.*l1.*l_S1.*l_S2.*m_G1.*m_G2.*t9.*t12)-t2.*t3.*t4.*t5.*t12.*t29.*t66.*2.0,0.0,0.0,1.0,-t24.*(t45+t46+t47+J_G2xx.*k_G1+k_G1.*m_G2.*t3+dphi1_t.*t2.*t3.*t4.*t5.*t12.*2.0),0.0,t24.*(t47+t67+t68+t69+k_G1.*l1.*l_S2.*m_G2.*t5+J_G1xx.*dphi1_t.*l1.*l_S2.*m_G2.*t12.*2.0+dphi1_t.*l1.*l_S2.*t2.*t4.*t12.*2.0+dphi1_t.*l1.*l_S2.*m_G1.*m_G2.*t6.*t12.*2.0),0.0,0.0,0.0,-t44-t24.*(t26+t27+t28-t2.*t3.*t4.*t10.*t11+g.*l1.*t3.*t4.*t5.*t21-l1.*l_S2.*t3.*t4.*t5.*t13-J_G2xx.*l1.*l_S2.*m_G2.*t5.*t13-dphi2_t.*k_G2.*l1.*l_S2.*m_G2.*t12+a_w.*l1.*t3.*t4.*t5.*t22-a_w.*l1.*t3.*t4.*t12.*t21),0.0,t24.*(t27+t49+t50+t51+t52+J_G1xx.*a_w.*l_S2.*m_G2.*t22+J_G1xx.*g.*l_S2.*m_G2.*t21+a_w.*l_S2.*t2.*t4.*t22+g.*l_S2.*t2.*t4.*t21-t2.*t3.*t4.*t10.*t13-g.*l_S2.*t2.*t4.*t9.*t12-l1.*l_S2.*t2.*t4.*t5.*t11-J_G1xx.*l1.*l_S2.*m_G2.*t5.*t11-dphi2_t.*k_G2.*l1.*l_S2.*m_G2.*t12+a_w.*l_S2.*m_G1.*m_G2.*t6.*t22+g.*l_S2.*m_G1.*m_G2.*t6.*t21-l1.*l_S2.*m_G1.*m_G2.*t5.*t6.*t11-g.*l1.*l_S1.*l_S2.*m_G1.*m_G2.*t9.*t12)+t2.*t3.*t4.*t5.*t12.*t29.*t66.*2.0,0.0,0.0,0.0,t24.*(t45+t46+t47-J_G2xx.*dphi2_t.*l1.*l_S2.*m_G2.*t12.*2.0-dphi2_t.*l1.*l_S2.*t3.*t4.*t12.*2.0),1.0,-t24.*(t47+t67+t68+t69-dphi2_t.*t2.*t3.*t4.*t5.*t12.*2.0)],[6,6]);
end